# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-27 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baoban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minjing',
            name='daiban_minjing',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], max_length=1, verbose_name='是否代班'),
        ),
        migrations.AlterField(
            model_name='minjing',
            name='danwei_minjing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baoban.org', verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='minjing',
            name='jinghao_minjing',
            field=models.CharField(max_length=8, verbose_name='警号'),
        ),
        migrations.AlterField(
            model_name='minjing',
            name='lingdao_minjing',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], max_length=1, verbose_name='是否狱长'),
        ),
        migrations.AlterField(
            model_name='minjing',
            name='name_minjing',
            field=models.CharField(max_length=12, verbose_name='民警姓名'),
        ),
        migrations.AlterField(
            model_name='minjing',
            name='w5c_minjing',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], max_length=1, verbose_name='五查值班'),
        ),
        migrations.AlterField(
            model_name='org',
            name='code_org',
            field=models.CharField(max_length=2, verbose_name='单位代码'),
        ),
        migrations.AlterField(
            model_name='org',
            name='memo_org',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='org',
            name='name_org',
            field=models.CharField(max_length=32, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='org',
            name='yafan_org',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], max_length=1, verbose_name='是否押犯'),
        ),
        migrations.AlterField(
            model_name='zfrenshu',
            name='danwei_zfrenshu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baoban.org', verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='zfrenshu',
            name='date_zfrenshu',
            field=models.DateField(auto_now_add=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='zfrenshu',
            name='jinbi_zfrenshu',
            field=models.IntegerField(verbose_name='禁闭'),
        ),
        migrations.AlterField(
            model_name='zfrenshu',
            name='jiuyi_zfrenshu',
            field=models.IntegerField(verbose_name='外出就医'),
        ),
        migrations.AlterField(
            model_name='zfrenshu',
            name='other_zfrenshu',
            field=models.IntegerField(verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='zfrenshu',
            name='shiya_zfrenshu',
            field=models.IntegerField(verbose_name='实押'),
        ),
        migrations.AlterField(
            model_name='zhiban',
            name='date_zhiban',
            field=models.DateField(auto_now_add=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='zhiban',
            name='fangbao_zhiban',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], max_length=1, verbose_name='防爆队员'),
        ),
        migrations.AlterField(
            model_name='zhiban',
            name='name_zhiban',
            field=models.ManyToManyField(to='baoban.minjing', verbose_name='值班民警'),
        ),
        migrations.AlterField(
            model_name='zhiban',
            name='yeban_zhiban',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], max_length=1, verbose_name='夜班'),
        ),
    ]
